//
// BarangayComplaintArray.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public typealias BarangayComplaintArray = [BarangayComplaintModel]
