//
// BarangayComplaintModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BarangayComplaintModel: Codable {

    public var complaintId: String?
    public var attachmentId: String?
    public var complaintDesc: String?
    public var latitude: String?
    public var longitude: String?
    public var type: String?
    public var userId: String?
    public var status: String?
    public var createDate: String?

    public init(complaintId: String?, attachmentId: String?, complaintDesc: String?, latitude: String?, longitude: String?, type: String?, userId: String?, status: String?, createDate: String?) {
        self.complaintId = complaintId
        self.attachmentId = attachmentId
        self.complaintDesc = complaintDesc
        self.latitude = latitude
        self.longitude = longitude
        self.type = type
        self.userId = userId
        self.status = status
        self.createDate = createDate
    }

    public enum CodingKeys: String, CodingKey { 
        case complaintId = "complaint_id"
        case attachmentId = "attachment_id"
        case complaintDesc = "complaint_desc"
        case latitude
        case longitude
        case type
        case userId = "user_id"
        case status
        case createDate = "create_date"
    }


}

