//
// BarangayPermitModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BarangayPermitModel: Codable {

    public var permitId: String?
    public var username: String?
    public var attachmentId: String?
    public var secNo: String?
    public var businessBuildingNo: String?
    public var businessStreet: String?
    public var businessActivity: String?
    public var businessName: String?
    public var capitalization: String?
    public var ctcNo: String?
    public var lessorBarangay: String?
    public var lessorBldgNo: String?
    public var lessorCity: String?
    public var lessorEmailaddr: String?
    public var lessorName: String?
    public var lessorProvince: String?
    public var lessorStreet: String?
    public var lessorSubdv: String?
    public var monthlyRental: String?
    public var noUnits: String?
    public var status: String?
    public var grossSale: String?

    public init(permitId: String?, username: String?, attachmentId: String?, secNo: String?, businessBuildingNo: String?, businessStreet: String?, businessActivity: String?, businessName: String?, capitalization: String?, ctcNo: String?, lessorBarangay: String?, lessorBldgNo: String?, lessorCity: String?, lessorEmailaddr: String?, lessorName: String?, lessorProvince: String?, lessorStreet: String?, lessorSubdv: String?, monthlyRental: String?, noUnits: String?, status: String?, grossSale: String?) {
        self.permitId = permitId
        self.username = username
        self.attachmentId = attachmentId
        self.secNo = secNo
        self.businessBuildingNo = businessBuildingNo
        self.businessStreet = businessStreet
        self.businessActivity = businessActivity
        self.businessName = businessName
        self.capitalization = capitalization
        self.ctcNo = ctcNo
        self.lessorBarangay = lessorBarangay
        self.lessorBldgNo = lessorBldgNo
        self.lessorCity = lessorCity
        self.lessorEmailaddr = lessorEmailaddr
        self.lessorName = lessorName
        self.lessorProvince = lessorProvince
        self.lessorStreet = lessorStreet
        self.lessorSubdv = lessorSubdv
        self.monthlyRental = monthlyRental
        self.noUnits = noUnits
        self.status = status
        self.grossSale = grossSale
    }

    public enum CodingKeys: String, CodingKey { 
        case permitId = "permit_id"
        case username
        case attachmentId = "attachment_id"
        case secNo = "sec_no"
        case businessBuildingNo = "business_building_no"
        case businessStreet = "business_street"
        case businessActivity = "business_activity"
        case businessName = "business_name"
        case capitalization
        case ctcNo = "ctc_no"
        case lessorBarangay = "lessor_barangay"
        case lessorBldgNo = "lessor_bldg_no"
        case lessorCity = "lessor_city"
        case lessorEmailaddr = "lessor_emailaddr"
        case lessorName = "lessor_name"
        case lessorProvince = "lessor_province"
        case lessorStreet = "lessor_street"
        case lessorSubdv = "lessor_subdv"
        case monthlyRental = "monthly_rental"
        case noUnits = "no_units"
        case status
        case grossSale = "gross_sale"
    }


}

