//
// BarangayEventModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BarangayEventModel: Codable {

    public var eventId: String?
    public var attachmentId: String?
    public var endDate: String?
    public var eventDesc: String?
    public var eventTitle: String?
    public var startDate: String?
    public var type: String?

    public init(eventId: String?, attachmentId: String?, endDate: String?, eventDesc: String?, eventTitle: String?, startDate: String?, type: String?) {
        self.eventId = eventId
        self.attachmentId = attachmentId
        self.endDate = endDate
        self.eventDesc = eventDesc
        self.eventTitle = eventTitle
        self.startDate = startDate
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case eventId = "event_id"
        case attachmentId = "attachment_id"
        case endDate = "end_date"
        case eventDesc = "event_desc"
        case eventTitle = "event_title"
        case startDate = "start_date"
        case type
    }


}

