//
// BarangayDocumentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BarangayDocumentModel: Codable {

    public var userId: String?
    public var username: String?
    public var expirationDate: String?
    public var governmentId: String?
    public var attachmentId: String?
    public var reason: String?
    public var status: String?

    public init(userId: String?, username: String?, expirationDate: String?, governmentId: String?, attachmentId: String?, reason: String?, status: String?) {
        self.userId = userId
        self.username = username
        self.expirationDate = expirationDate
        self.governmentId = governmentId
        self.attachmentId = attachmentId
        self.reason = reason
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case userId = "user_id"
        case username
        case expirationDate = "expiration_date"
        case governmentId = "government_id"
        case attachmentId = "attachment_id"
        case reason
        case status
    }


}

