//
// BarangayUserModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BarangayUserModel: Codable {

    public var userId: String?
    public var username: String?
    public var password: String?
    public var address: String?
    public var birtdate: String?
    public var createdate: String?
    public var firstname: String?
    public var lastname: String?
    public var mobilenumber: String?
    public var zipcode: String?
    public var civilStatus: String?
    public var ctcNo: String?
    public var tinNo: String?
    public var placeOfBirth: String?
    public var weight: String?
    public var height: String?
    public var controlNo: String?
    public var contactNo: String?
    public var profession: String?
    public var grossIncome: String?
    public var attachmentId: String?
    public var gender: String?

    public init(userId: String?, username: String?, password: String?, address: String?, birtdate: String?, createdate: String?, firstname: String?, lastname: String?, mobilenumber: String?, zipcode: String?, civilStatus: String?, ctcNo: String?, tinNo: String?, placeOfBirth: String?, weight: String?, height: String?, controlNo: String?, contactNo: String?, profession: String?, grossIncome: String?, attachmentId: String?, gender: String?) {
        self.userId = userId
        self.username = username
        self.password = password
        self.address = address
        self.birtdate = birtdate
        self.createdate = createdate
        self.firstname = firstname
        self.lastname = lastname
        self.mobilenumber = mobilenumber
        self.zipcode = zipcode
        self.civilStatus = civilStatus
        self.ctcNo = ctcNo
        self.tinNo = tinNo
        self.placeOfBirth = placeOfBirth
        self.weight = weight
        self.height = height
        self.controlNo = controlNo
        self.contactNo = contactNo
        self.profession = profession
        self.grossIncome = grossIncome
        self.attachmentId = attachmentId
        self.gender = gender
    }

    public enum CodingKeys: String, CodingKey { 
        case userId = "user_id"
        case username
        case password
        case address
        case birtdate
        case createdate
        case firstname
        case lastname
        case mobilenumber
        case zipcode
        case civilStatus = "civil_status"
        case ctcNo = "ctc_no"
        case tinNo = "tin_no"
        case placeOfBirth = "place_of_birth"
        case weight
        case height
        case controlNo = "control_no"
        case contactNo = "contact_no"
        case profession
        case grossIncome = "gross_income"
        case attachmentId = "attachment_id"
        case gender
    }


}

