# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BarangayInformationManagementSystem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BarangayInformationManagementSystem
  pod 'RATreeView', '~> 2.1.2'
  pod 'LNZTreeView'
  pod 'CollectionViewSlantedLayout', '~> 3.1'
  pod 'RAMAnimatedTabBarController'
  pod 'RAMReel'
  pod 'RAMAnimatedTabBarController'
  pod 'MagazineLayout'
  pod 'CollectionKit'
  pod 'CollectionKit/WobbleAnimator'
  pod 'JTAppleCalendar', '~> 7.1'
  pod 'FSCalendar'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'FoldingCell'
  pod 'LGButton'
  pod 'TransitionButton'
  pod 'YPImagePicker'
  pod 'AWSAPIGateway'
  pod 'AWSS3'
  pod 'Pickle'
  pod 'Eureka', '~> 4.0'
  pod 'Alamofire'
  pod 'JASON', '~> 3.0'
  pod 'paper-onboarding'
  pod 'SwiftyAvatar', '~> 1.1'
  pod 'GenericPasswordRow', '~> 3.0'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod 'AWSUserPoolsSignIn'
  pod 'AWSAuthUI'
  #pod 'AWSCognitoAuth'
  # pod 'AWSMobileClient', '~> 2.6.13'
pod 'TweeTextField'
  
  # other pods . . .
  pod 'AWSMobileClient', '~> 2.9.0'
  target 'BarangayInformationManagementSystemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BarangayInformationManagementSystemUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
