# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BarangayInformationManagementSystem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BarangayInformationManagementSystem
  pod 'RATreeView', '~> 2.1.2'
  pod 'LNZTreeView'
  pod 'CollectionViewSlantedLayout', '~> 3.1'
  pod 'RAMAnimatedTabBarController'
  pod 'RAMReel'
  pod 'RAMAnimatedTabBarController'
  pod 'MagazineLayout'
  pod 'CollectionKit'
  pod 'CollectionKit/WobbleAnimator'
  pod 'JTAppleCalendar', '~> 7.1'
  pod 'FSCalendar'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'FoldingCell'
  pod 'LGButton'
  pod 'TransitionButton'
  target 'BarangayInformationManagementSystemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BarangayInformationManagementSystemUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
