//
// BarangayAttachmentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BarangayAttachmentModel: Codable {

    public var attachmentId: String?
    public var attachmentSrc: String?

    public init(attachmentId: String?, attachmentSrc: String?) {
        self.attachmentId = attachmentId
        self.attachmentSrc = attachmentSrc
    }

    public enum CodingKeys: String, CodingKey { 
        case attachmentId = "attachment_id"
        case attachmentSrc = "attachment_src"
    }


}

