//
// BarangayDocumentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BarangayDocumentModel: Codable {

    public var documentId: String?
    public var approveDate: String?
    public var attachmentId: String?
    public var createDate: String?
    public var status: String?
    public var reason: String?
    public var userId: String?

    public init(documentId: String?, approveDate: String?, attachmentId: String?, createDate: String?, status: String?, reason: String?, userId: String?) {
        self.documentId = documentId
        self.approveDate = approveDate
        self.attachmentId = attachmentId
        self.createDate = createDate
        self.status = status
        self.reason = reason
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey { 
        case documentId = "document_id"
        case approveDate = "approve_date"
        case attachmentId = "attachment_id"
        case createDate = "create_date"
        case status
        case reason
        case userId = "user_id"
    }


}

